name: WPScripts Lint Action
author: Samuel Meuli
description: GitHub Action for detecting and fixing WP theme/plugin linting errors

inputs:
  github_token:
    description: The GitHub token used to authenticated with GitHub.
    required: false
    default: ${{ github.token }}
  continue_on_error:
    description: Whether the workflow run should also fail when linter failures are detected
    required: false
    default: "true"
  auto_fix:
    description: Whether linters should try to fix code style issues automatically
    required: false
    default: "false"
  git_no_verify:
    description: Bypass the pre-commit and pre-push git hooks
    required: false
    default: "false"
  git_name:
    description: Username for auto-fix commits
    required: false
    default: Lint Action
  git_email:
    description: Email address for auto-fix commits
    required: false
    default: "info@sixa.ch"
  commit_message:
    description: 'Template for auto-fix commit messages. The "${linter}" variable can be used to insert the name of the linter which has created the auto-fix'
    required: false
    default: "Fix code style issues with ${linter}"
  check_name:
    description: 'Template for the name of the check run. The "${linter}" and "${dir}" variables can be used to insert the name and directory of the linter.'
    required: false
    default: "${linter}"
  neutral_check_on_warning:
    description: Whether the check run should conclude with a neutral status instead of success when the linter finds only warnings
    required: false
    default: "false"

  # CSS

  stylelint:
    description: Enable or disable stylelint checks
    required: false
    default: "false"
  stylelint_args:
    description: Additional arguments to pass to the linter
    required: false
    default: ""
  stylelint_dir:
    description: Directory where the stylelint command should be run
    required: false
  stylelint_extensions:
    description: Extensions of files to check with stylelint
    required: false
    default: "css,sass,scss"
  stylelint_command_prefix:
    description: Shell command to prepend to the linter command
    required: false
    default: ""

  # JavaScript

  eslint:
    description: Enable or disable ESLint checks
    required: false
    default: "false"
  eslint_args:
    description: Additional arguments to pass to the linter
    required: false
    default: ""
  eslint_dir:
    description: Directory where the ESLint command should be run
    required: false
  eslint_extensions:
    description: Extensions of files to check with ESLint
    required: false
    default: "js"
  eslint_command_prefix:
    description: Shell command to prepend to the linter command. Will default to `npx --no-install` for NPM and `yarn run --silent` for Yarn.
    required: false
    default: ""

  prettier:
    description: Enable or disable Prettier checks
    required: false
    default: "false"
  prettier_args:
    description: Additional arguments to pass to the linter
    required: false
    default: ""
  prettier_dir:
    description: Directory where the Prettier command should be run
    required: false
  prettier_extensions:
    description: Extensions of files to check with Prettier
    required: false
    default: "css,html,js,json,jsx,md,sass,scss,ts,tsx,vue,yaml,yml"
  prettier_command_prefix:
    description: Shell command to prepend to the linter command. Will default to `npx --no-install` for NPM and `yarn run --silent` for Yarn.
    required: false
    default: ""

  # PHP

  php_codesniffer:
    description: Enable or disable PHP_CodeSniffer checks
    required: false
    default: "false"
  php_codesniffer_args:
    description: Additional arguments to pass to the linter
    required: false
    default: ""
  php_codesniffer_dir:
    description: Directory where the PHP_CodeSniffer command should be run
    required: false
  php_codesniffer_extensions:
    description: Extensions of files to check with PHP_CodeSniffer
    required: false
    default: "php"
  php_codesniffer_command_prefix:
    description: Shell command to prepend to the linter command
    required: false
    default: ""

runs:
  using: node12
  main: ./dist/index.js

branding:
  icon: check
  color: green
