name: WPScripts Lint Action
author: Sixa
description: GitHub Action for detecting and fixing WP theme/plugin linting errors

inputs:
  github_token:
    description: The GitHub token used to authenticated with GitHub.
    required: false
    default: ${{ github.token }}
  continue_on_error:
    description: Whether the workflow run should also fail when linter failures are detected
    required: false
    default: "true"
  fix_mode:
    description: Whether linters should try to fix code style issues automatically
    required: false
    default: "false"
  git_no_verify:
    description: Bypass the pre-commit and pre-push git hooks
    required: false
    default: "false"
  git_name:
    description: Username for auto-fix commits
    required: false
    default: Lint Action
  git_email:
    description: Email address for auto-fix commits
    required: false
    default: "info@sixa.ch"
  commit_message:
    description: 'Template for auto-fix commit messages. The "${linter}" variable can be used to insert the name of the linter which has created the auto-fix'
    required: false
    default: "Fix code style issues with ${linter}"
  check_name:
    description: 'Template for the name of the check run. The "${linter}" and "${dir}" variables can be used to insert the name and directory of the linter.'
    required: false
    default: "${linter}"
  neutral_check_on_warning:
    description: Whether the check run should conclude with a neutral status instead of success when the linter finds only warnings
    required: false
    default: "false"

  # Format

  format:
    description: Run WPScripts Format command to fix prettier styling
    required: false
    default: "false"
  format_args:
    description: Additional arguments to pass to the format
    required: false
    default: ""
  format_dir:
    description: Directory where the WPScripts Format command should be run
    required: false
  format_prefix:
    description: Shell command to prepend to the format command
    required: false
    default: ""

  # CSS

  lint_style:
    description: Enable or disable WPScripts Lint Style checks
    required: false
    default: "false"
  lint_style_args:
    description: Additional arguments to pass to the linter
    required: false
    default: ""
  lint_style_dir:
    description: Directory where the WPScripts Lint Style command should be run
    required: false
  lint_style_prefix:
    description: Shell command to prepend to the linter command
    required: false
    default: ""

  # JavaScript

  lint_js:
    description: Enable or disable WPScripts Lint JS check
    required: false
    default: "false"
  lint_js_args:
    description: Additional arguments to pass to the linter
    required: false
    default: ""
  lint_js_dir:
    description: Directory where the WPScripts Lint JS command should be run
    required: false
  lint_js_prefix:
    description: Shell command to prepend to the linter command. Will default to `npx --no-install` for NPM and `yarn run --silent` for Yarn.
    required: false
    default: ""

  # JavaScript in Markdown

  lint_md_js:
    description: Enable or disable WPScripts Lint Markdown JS check
    required: false
    default: "false"
  lint_md_js_args:
    description: Additional arguments to pass to the linter
    required: false
    default: ""
  lint_md_js_dir:
    description: Directory where the WPScripts Lint Markdown JS command should be run
    required: false
  lint_md_js_prefix:
    description: Shell command to prepend to the linter command. Will default to `npx --no-install` for NPM and `yarn run --silent` for Yarn.
    required: false
    default: ""

runs:
  using: node12
  main: ./dist/index.js

branding:
  icon: check
  color: green
